#!/bin/sh

export ADMIN_USERNAME=admin
export ADMIN_PASSWORD=admin

ENABLED=${ENABLED:-yes}
PROCS=songloft
EXEHOME=/opt/var/lib/songloft
PREARGS="start-stop-daemon -S -b -m -p /opt/var/run/$PROCS.pid -d $EXEHOME"
ARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
